### ISSUE TITLE
Show all buttons for credit and debit

### ISSUE THREAD

**Issue by DavidM42** [Merzlabs/finanztopf#11]
User story:
You want to have an overview of all your credit and debit transaction to figure out categories.
Wenn you click "Zahlungseingänge" you want so see all "credit" transactions like you do for categories and when you click on "Zahlungsausgänge" you want to see all "debit" transactions like it is a filter.

**Comment by NiklasMerz** [comment]
Already started but revert because of complex component structure. We need to consider refactoring or building outputs.

Detail page now allows to show entries instead of categories aa7029f6c9105271b87d8c633e4506e431e2c134
